name: Spark library CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        spark-version: [ 3.0.1, 3.0.2, 3.0.3, 3.1.2, 3.2.1, 3.2.4, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.5.0 ]

    steps:
    - uses: actions/checkout@v3.5.2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Run tests and produce coverage
      run: sbt -DsparkVersion="${{matrix.sparkVersion}}" clean coverageOn test coverageReport

#    - name: Upload coverage to CodeCov
#      uses: codecov/codecov-action@v3.1.4
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        files: ./target/spark-${{ matrix.sparkVersion }}/scala-2.12/coverage-report/cobertura.xml
#        env_vars: ${{ matrix.sparkVersion }}
#        fail_ci_if_error: true
#        name: spark-cef-reader
#        verbose: true

    - name: Create package
      if: ${{ github.event_name != 'pull_request' }}
      run: sbt -DsparkVersion="${{matrix.sparkVersion}}" clean coverageOff package

    - name: Upload the package
      uses: actions/upload-artifact@v3.1.2
      with:
        path: ./target/**/spark-cef-reader*.jar
        if-no-files-found: warn
